version: "3.4"
services:
#  crawler_1:
#    container_name: crawler
#    build:
#      dockerfile: Dockerfile
#      context: ./crawler
#    volumes:
#      - "./crawler/app:/src/app"
#    ports:
#      - 3000:3000
      
  parser_1:
    container_name: parser_1
    build:
      dockerfile: Dockerfile
      context: ./parser
    volumes:
      - "./parser/app:/src/app"
    ports:
      - "4001:4001"


  storage_1:
    container_name: storage_1
    build:
      dockerfile: Dockerfile
      context: ./storage
    volumes:
      - "./storage/app:/src/app"
    ports:
      - "5001:5001"
    depends_on:
      - mongo_storage_1

  streamer_1:
    container_name: streamer_1
    build:
      dockerfile: Dockerfile
      context: ./streamer
    volumes:
      - "./streamer/app:/src/app"
    ports:
      - "7001:7001"
      - "9001:9001"

  mongo_storage_1:
    container_name: mongo_storage_1
    image: mongo:latest
    logging:
      driver: "none"
    ports:
      - "27017:27017"
    volumes:
      - ./data/db-mongo_storage_1:/data/db




